/*
 * This file is generated by jOOQ.
 */
package com.moneytransfer.model;


import com.moneytransfer.model.tables.Users;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Accounts extends SchemaImpl {

    private static final long serialVersionUID = -1447981512;

    /**
     * The reference instance of <code>accounts</code>
     */
    public static final Accounts ACCOUNTS = new Accounts();

    /**
     * The table <code>accounts.accounts</code>.
     */
    public final com.moneytransfer.model.tables.Accounts ACCOUNTS_ = com.moneytransfer.model.tables.Accounts.ACCOUNTS_;

    /**
     * The table <code>accounts.users</code>.
     */
    public final Users USERS = com.moneytransfer.model.tables.Users.USERS;

    /**
     * No further instances allowed
     */
    private Accounts() {
        super("accounts", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            com.moneytransfer.model.tables.Accounts.ACCOUNTS_,
            Users.USERS);
    }
}
