/*
 * This file is generated by jOOQ.
 */
package com.moneytransfer.model;


import com.moneytransfer.model.tables.Accounts;
import com.moneytransfer.model.tables.Users;
import com.moneytransfer.model.tables.records.AccountsRecord;
import com.moneytransfer.model.tables.records.UsersRecord;

import javax.annotation.processing.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>accounts</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AccountsRecord, Integer> IDENTITY_ACCOUNTS_ = Identities0.IDENTITY_ACCOUNTS_;
    public static final Identity<UsersRecord, Integer> IDENTITY_USERS = Identities0.IDENTITY_USERS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccountsRecord> KEY_ACCOUNTS_PRIMARY = UniqueKeys0.KEY_ACCOUNTS_PRIMARY;
    public static final UniqueKey<AccountsRecord> KEY_ACCOUNTS_IDX_ACC = UniqueKeys0.KEY_ACCOUNTS_IDX_ACC;
    public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = UniqueKeys0.KEY_USERS_PRIMARY;
    public static final UniqueKey<UsersRecord> KEY_USERS_IDX_UE = UniqueKeys0.KEY_USERS_IDX_UE;
    public static final UniqueKey<UsersRecord> KEY_USERS_USERS_USER_LOGIN_UINDEX = UniqueKeys0.KEY_USERS_USERS_USER_LOGIN_UINDEX;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<AccountsRecord, Integer> IDENTITY_ACCOUNTS_ = Internal.createIdentity(Accounts.ACCOUNTS_, Accounts.ACCOUNTS_.ACCOUNT_ID);
        public static Identity<UsersRecord, Integer> IDENTITY_USERS = Internal.createIdentity(Users.USERS, Users.USERS.USER_ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<AccountsRecord> KEY_ACCOUNTS_PRIMARY = Internal.createUniqueKey(Accounts.ACCOUNTS_, "KEY_accounts_PRIMARY", Accounts.ACCOUNTS_.ACCOUNT_ID);
        public static final UniqueKey<AccountsRecord> KEY_ACCOUNTS_IDX_ACC = Internal.createUniqueKey(Accounts.ACCOUNTS_, "KEY_accounts_idx_acc", Accounts.ACCOUNTS_.ACCOUNT_NAME, Accounts.ACCOUNTS_.CCY);
        public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = Internal.createUniqueKey(Users.USERS, "KEY_users_PRIMARY", Users.USERS.USER_ID);
        public static final UniqueKey<UsersRecord> KEY_USERS_IDX_UE = Internal.createUniqueKey(Users.USERS, "KEY_users_idx_ue", Users.USERS.USER_LOGIN);
        public static final UniqueKey<UsersRecord> KEY_USERS_USERS_USER_LOGIN_UINDEX = Internal.createUniqueKey(Users.USERS, "KEY_users_users_User_Login_uindex", Users.USERS.USER_LOGIN);
    }
}
